version: "3.8"
services:
  back:
    stdin_open: true
    image: node:16.9.0-stretch
    working_dir: "/back"
    command: sh -c "yarn install && yarn start:dev"
    ports:
      - "3001:3000"
    volumes:
      - "./back:/back"
    environment:
      NODE_ENV: development
      DATABASE_URL: mongodb://root:example@mongo:27017/idiomaplay?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.3-focal
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
    depends_on:
      - mongo

  # Support for mobile is not optimal, therefore it's disabled
  # and expo should be run natively
  #  mobile:
  #    stdin_open: true
  #    image: node:16.9.0-stretch
  #    working_dir: "/mobile"
  #    command: sh -c "yarn install && yarn start"
  #    ports:
  #      - "19000:19000"
  #      - "19002:19002"
  #    environment:
  #      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
  #    volumes:
  #      - "./mobile:/mobile"

volumes:
  mongo-data:
