version: "3.8"
services:
  back:
    stdin_open: true
    image: node:16.9.0-stretch
    working_dir: "/back"
    command: sh -c "yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - "./back:/back"

  mobile:
    stdin_open: true
    image: node:16.9.0-stretch
    working_dir: "/mobile"
    command: sh -c "yarn install && yarn start"
    ports:
      - "19000:19000"
      - "19002:19002"
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - "./mobile:/mobile"
