version: "3.8"
services:
  back:
    stdin_open: true
    image: node:16.9.0-stretch
    working_dir: "/back"
    command: sh -c "yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - "./back:/back"
    environment:
      NODE_ENV: development
      DATABASE_URL: mongodb://db:27017/idiomaplaydb
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    restart: always

