export const colors = {
  PRIMARY: '#4db6ac',
  PRIMARY_DARK: '#00867d',
  PRIMARY_LIGHT: '#82e9de',

  SECONDARY: '#F8c49c',

  SECONDARY: '#ffa000',
  SECONDARY_DARK: '#c67100',
  SECONDARY_LIGHT: '#ffd149',

  PRIMARY_BUTTON_COLOR: '#9c27b0',
  PRIMARY_BUTTON_DARK_COLOR: '#6a0080',
  PRIMARY_BUTTON_LIGHT_COLOR: '#d05ce3',

  SECONDARY_BUTTON_COLOR: '#ffa000',
  SECONDARY_BUTTON_DARK_COLOR: '',
  SECONDARY_BUTTON_LIGHT_COLOR: '',

  BACKGROUND: '#ffffff',
  LIGHT_GRAY: '#eeeeee',
  DARK_GRAY: '#bcbcbc',

  CORRECT_COLOR: '#2e7d32',
  INCORRECT_COLOR: '#f44336',
  
  DARK_LOGO: '#606060'
};
