export const colors = {
  PRIMARY: '#4db6ac',
  PRIMARY_DARK: '#00867d',
  PRIMARY_LIGHT: '#82e9de',

  SECONDARY: '#ffa000',
  SECONDARY_DARK: '#c67100',
  SECONDARY_LIGHT: '#ffd149',

  PRIMARY_BUTTON_COLOR: '#9c27b0',
  PRIMARY_BUTTON_DARK_COLOR: '#6a0080',
  PRIMARY_BUTTON_LIGHT_COLOR: '#d05ce3',

  SECONDARY_BUTTON_COLOR: '',

  BACKGROUND: '#ffffff',

  CORRECT_COLOR: '#2e7d32',
  INCORRECT_COLOR: '#f44336',
};
