name: back
on:
  pull_request:
    paths:
      - "back/**"
  push:
    paths:
      - "back/**"
env:
  SERVICE: back
  REGISTRY_URL: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ghcr.io/tdp-final-game/idiomaplay-back
  IMAGE_VERSION: ${{ github.sha }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: .github/scripts/run_tests.sh

  package:
    runs-on: ubuntu-20.04
    if: contains('refs/heads/main', github.ref)
    needs: 'test'
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Package image
        run: .github/scripts/package.sh

  deploy:
    runs-on: ubuntu-20.04
    if: contains('refs/heads/main', github.ref)
    needs: 'package'
    permissions:
      packages: read
    steps:
      - name: Deploy to heroku
        run: .github/scripts/deploy_to_heroku.sh
